config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  root to: 'homes#top'
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  get 'home/about'=> 'homes#about'
  
  get '/search' => 'search#search'
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
 
  
  validates :title, presence: true
  validates :body, presence: true ,length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully"
       redirect_to book_path(@book.id)
    else
       @books = Book.all
       @user = current_user
       render :index
    end
  end
  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
    
  end
  def show
    @books = Book.all
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @book_comment = BookComment.new
  end
  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
       render "edit"
    else
       redirect_to books_path
    end
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "You have updated book successfully."
       redirect_to book_path(@book.id)
    else
       render :edit
    end
  end
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
 

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
    <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
        	  <th>name</th>
        	  <th><%= user.name %></th>
          </tr>
          <tr>
        	  <th>introduction</th>
        	  <th><%= user.introduction %></th>
        	</tr>
        	<tr>
        	  <th>フォロー数:
          	    <%= link_to user_followings_path(user) do %>
          	    <%= user.followings.count %>
          	  <% end %></th>
          	  <th></th>
          </tr>
          <tr>
            <th>フォロワー数:
              <%= link_to user_followers_path(user) do %>
                <%= user.followers.count %>
              <% end %></th>
              <th></th>
          </tr>
          <tr>
        	  <th><% if current_user != user %>
          	      <% if current_user.following?(user) %>
                    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
                  <% end %>
                <% end %></th>
              <th></th>
          </tr>
          </tbody>
      </table>
        <div class="row">
        <% if current_user == user %>
          <%= link_to '', edit_user_path(user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user" %>
        <% end %>
        </div>



         <h2 class="mt-3">New book</h2>
          <%= form_with model:book, local:true do |f| %>
          <h4>title</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_field :body %>
          <%= f.submit 'Create Book' %>
        <% end %>
    </div>

app/views/books/edit.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <% if @book.errors.any? %>
          <%= @book.errors.count %> errors prohibited this obj from being saved:
          <% @book.errors.full_messages.each do |message| %>
          <%= message %>
          <% end %>
      <% end %>
      <h2>Editing Book</h2>
      <%= form_with model:@book, local:true do |f| %>
      <tr>title<tr>
      <%= f.text_field :title, autofocus: true, id:"inputName", placeholder:"title"%>

      <tr>Opinion</tr>
      <%= f.text_field :body, autofocus: true, id:"inputbody", placeholder:"Opinion"%>
      <%= f.submit "Update Book" %>
      <% end %><br>
      <%= link_to "Show | ", book_path %>
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
<% end %>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/list', book: @book, user: @user %>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
              <tr>
                <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= link_to book.body, book_path(book.id) %></td>
                <td id="favorite_buttons_<%= book.id %>"> <%= render "favorites/favorite",book: book %></td>
                <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
              <tr>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>
  </div>

app/views/books/show.html.erb
 <% if flash[:notice] %>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
  <%= render 'books/list', book: @book_,user: @user %>
    <div class="col-md-8 offset-md-1">
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>Book detail</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>

          <tr>
            <td><%= link_to user_path(@user) do %>
            <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg" , :size =>'40x40' %>
            <% end %><br>
            <%= link_to @user.name, user_path(@user) %>
            </td>
            <td><%= link_to @book.title, book_path %></td>
            <td><%= @book.body %></td>
            <td><% if @user.id == current_user.id %>
              <%= link_to "Edit", edit_book_path(@book) ,class: "btn btn-sm btn-success" %>
              <%= link_to "Destroy", book_path(@book.id), method: :delete, "data confirm"=>"本当に消しますか？", class: "btn btn-sm btn-danger" %>
            <% end %></td>
            <td id="favorite_buttons_<%= @book.id %>">
            <%= render "favorites/favorite",book: @book %>
            </td>
          </tr>
        </tbody>
      </table>
      <table>
        <tbody id="comment_<%= @book.id %>" class="table table-striped">
          <%= render "post_comments/post_comment",book: @book %>
        </tbody>
      </table>
            <%= form_with(model:[@book, @book_comment], remote: true) do |f| %>
              <%= f.text_area :comment, size: "100x5", placeholder: "コメントをここに" %>
              <%= f.submit "送信する" %>
            <% end %>
    </div>